
// This configuration defines the structure of the disaster report for export and UI rendering.
// It allows for modular checklist creation across different disaster types.

export const DISASTER_REPORT_TEMPLATE = {
  version: "1.0.0",
  sections: [
    {
      id: "header",
      label: "Situation Header",
      required: true,
      fields: ["metadata.eventId", "metadata.disasterType", "metadata.severity", "metadata.location"]
    },
    {
      id: "risk",
      label: "Risk Assessment",
      required: true,
      fields: ["riskAssessment.immediateRisk", "riskAssessment.trajectoryPrediction"]
    },
    {
      id: "env",
      label: "Environmental Context",
      required: false,
      fields: ["riskAssessment.environmentalFactors"]
    },
    {
      id: "strategy",
      label: "Intervention Strategy",
      required: true,
      fields: ["interventionStrategy.immediateActions", "interventionStrategy.resourceAllocation"]
    },
    {
      id: "evac",
      label: "Evacuation Plan",
      required: false,
      fields: ["interventionStrategy.evacuationPlan"]
    },
    {
      id: "comms",
      label: "Communication",
      required: true,
      fields: ["communicationStrategy.publicAlerts", "communicationStrategy.officialUpdates"]
    }
  ],
  exportConfig: {
    pdf: {
      includeImages: true,
      includeQR: true,
      watermark: "CONFIDENTIAL DRAFT",
      footer: "Generated by CropHealth Monitor AI"
    },
    csv: {
      flattenNested: true,
      separator: ","
    }
  }
};

export const getReportVersion = () => {
  const date = new Date().toISOString().split('T')[0];
  return `v${DISASTER_REPORT_TEMPLATE.version}-${date}`;
};
