
import React, { useEffect, useState, useRef } from 'react';
import jsPDF from 'jspdf';
import QRCode from 'qrcode';
import * as XLSX from 'xlsx';
import { safeWriteExcelFile } from '../utils/safeExcelHandler';
import { FarmData, HealthReport } from '../types';

interface TrendPoint {
  date: string;
  healthScore: number;
  ndvi: number;
}

interface ShareReportProps {
  report: HealthReport;
  farm: FarmData;
  trendData?: TrendPoint[];
  onClose: () => void;
  shareUrl: string;
  isCopied: boolean;
  onCopy: () => void;
  onEmail?: () => void;
}

type Language = 'en' | 'es' | 'pt' | 'hi';

const TRANSLATIONS = {
  en: {
    title: "CropHealth Analysis",
    generated: "Generated on",
    farmDetails: "Farm Details",
    location: "Location",
    crop: "Crop",
    size: "Size",
    date: "Scan Date",
    gust: "Gust Wind",
    healthIndex: "Overall Health Index",
    primaryStress: "Primary Diagnosis",
    affected: "Area Affected",
    soil: "Soil Composition",
    ph: "pH Level",
    nitrogen: "Nitrogen (N)",
    phosphorus: "Phosphorus (P)",
    potassium: "Potassium (K)",
    organic: "Organic Matter",
    moisture: "Soil Moisture",
    summary: "Analysis Summary",
    interventions: "Recommended Interventions",
    plan: "Monitoring Plan",
    action: "Action",
    timing: "Timing",
    cost: "Cost",
    impact: "Impact",
    confidence: "Confidence",
    materials: "Materials",
    footer: "Generated by CropHealth Monitor",
    shareLink: "Share Link"
  },
  es: {
    title: "Análisis de Salud de Cultivos",
    generated: "Generado el",
    farmDetails: "Detalles de la Granja",
    location: "Ubicación",
    crop: "Cultivo",
    size: "Tamaño",
    date: "Fecha de Escaneo",
    gust: "Ráfaga de Viento",
    healthIndex: "Índice General de Salud",
    primaryStress: "Diagnóstico Principal",
    affected: "Área Afectada",
    soil: "Composición del Suelo",
    ph: "Nivel de pH",
    nitrogen: "Nitrógeno (N)",
    phosphorus: "Fósforo (P)",
    potassium: "Potasio (K)",
    organic: "Materia Orgánica",
    moisture: "Humedad del Suelo",
    summary: "Resumen del Análisis",
    interventions: "Intervenciones Recomendadas",
    plan: "Plan de Monitoreo",
    action: "Acción",
    timing: "Tiempo",
    cost: "Costo",
    impact: "Impacto",
    confidence: "Confianza",
    materials: "Materiales",
    footer: "Generado por CropHealth Monitor",
    shareLink: "Enlace para compartir"
  },
  pt: {
    title: "Análise de Saúde da Colheita",
    generated: "Gerado em",
    farmDetails: "Detalhes da Fazenda",
    location: "Localização",
    crop: "Cultura",
    size: "Tamanho",
    date: "Data da Varredura",
    gust: "Rajada de Vento",
    healthIndex: "Índice Geral de Saúde",
    primaryStress: "Diagnóstico Principal",
    affected: "Área Afetada",
    soil: "Composição do Solo",
    ph: "Nível de pH",
    nitrogen: "Nitrogênio (N)",
    phosphorus: "Fósforo (P)",
    potassium: "Potássio (K)",
    organic: "Matéria Orgânica",
    moisture: "Umidade do Solo",
    summary: "Resumo da Análise",
    interventions: "Intervenções Recomendadas",
    plan: "Plano de Monitoramento",
    action: "Ação",
    timing: "Tempo",
    cost: "Costo",
    impact: "Impacto",
    confidence: "Confiança",
    materials: "Materiais",
    footer: "Gerado por CropHealth Monitor",
    shareLink: "Link de compartilhamento"
  },
  hi: {
    title: "फसल स्वास्थ्य विश्लेषण",
    generated: "उत्पन्न तिथि",
    farmDetails: "खेत का विवरण",
    location: "स्थान",
    crop: "फसल",
    size: "आकार",
    date: "स्कैन तिथि",
    gust: "हवा का झोंका",
    healthIndex: "कुल स्वास्थ्य सूचकांक",
    primaryStress: "प्राथमिक निदान",
    affected: "प्रभावित क्षेत्र",
    soil: "मिट्टी की संरचना",
    ph: "pH स्तर",
    nitrogen: "नाइट्रोजन (N)",
    phosphorus: "फास्फोरस (P)",
    potassium: "पोटैशियम (K)",
    organic: "कार्बनिक पदार्थ",
    moisture: "मिट्टी की नमी",
    summary: "विश्लेषण सारांश",
    interventions: "अनुशंसित हस्तक्षेप",
    plan: "निगरानी योजना",
    action: "कार्य",
    timing: "समय",
    cost: "लागत",
    impact: "प्रभाव",
    confidence: "आत्मविश्वास",
    materials: "सामग्री",
    footer: "CropHealth Monitor द्वारा निर्मित",
    shareLink: "शेयर लिंक"
  }
};

const SECTIONS = [
  { id: 'details', label: 'Farm Details' },
  { id: 'metrics', label: 'Weather & Soil' },
  { id: 'health', label: 'Health Analysis' },
  { id: 'interventions', label: 'Interventions' },
  { id: 'plan', label: 'Monitoring Plan' }
];

const INTERVENTION_COLUMNS = [
  { id: 'action', label: 'Action/Title' },
  { id: 'timing', label: 'Timing' },
  { id: 'cost', label: 'Cost' },
  { id: 'impact', label: 'Impact' },
  { id: 'confidence', label: 'Confidence' },
  { id: 'materials', label: 'Materials' }
];

const FONTS = [
  { label: 'Helvetica (Sans)', value: 'helvetica' },
  { label: 'Times (Serif)', value: 'times' },
  { label: 'Courier (Mono)', value: 'courier' }
];

// Helper to convert URL to Base64
const imageUrlToBase64 = async (url: string): Promise<string | null> => {
  try {
    const response = await fetch(url, { mode: 'cors' });
    if (!response.ok) return null;
    const blob = await response.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch (error) {
    console.warn('Failed to load image for PDF:', error);
    return null;
  }
};

const ShareReport: React.FC<ShareReportProps> = ({ 
  report, 
  farm, 
  trendData,
  onClose,
  shareUrl,
  isCopied,
  onCopy,
  onEmail
}) => {
  const modalRef = useRef<HTMLDivElement>(null);

  // --- Main Mode State ---
  const [mode, setMode] = useState<'share' | 'export'>('share');

  // --- Export Settings State ---
  const [format, setFormat] = useState<'pdf' | 'xlsx' | 'csv' | 'json'>('pdf');
  const [language, setLanguage] = useState<Language>('en');
  const [activeSections, setActiveSections] = useState<string[]>(SECTIONS.map(s => s.id));
  const [includeMetadata, setIncludeMetadata] = useState(true);
  
  // PDF Settings
  const [pdfFont, setPdfFont] = useState('helvetica');
  const [pdfScale, setPdfScale] = useState(1.0);
  const [pdfOrientation, setPdfOrientation] = useState<'p' | 'l'>('p');

  // CSV Settings
  const [csvDelimiter, setCsvDelimiter] = useState<',' | ';' | '\t'>(',');
  const [csvColumns, setCsvColumns] = useState<string[]>(['action', 'timing', 'cost', 'impact', 'materials']);

  // Excel Settings
  const [xlsxSheetName, setXlsxSheetName] = useState('Analysis');
  const [xlsxLayout, setXlsxLayout] = useState<'compact' | 'spacious'>('spacious');

  // JSON Settings
  const [jsonPretty, setJsonPretty] = useState(true);

  // Preview State
  const [previewContent, setPreviewContent] = useState<string | null>(null);
  const [qrDataUrl, setQrDataUrl] = useState<string>('');
  
  // Loaded images for PDF
  const [pdfImages, setPdfImages] = useState<{ satellite?: string, logo?: string }>({});

  // --- Effects ---
  useEffect(() => {
    if (modalRef.current) modalRef.current.focus();
    document.body.style.overflow = 'hidden';
    return () => { document.body.style.overflow = 'auto'; };
  }, []);

  // Load images for PDF
  useEffect(() => {
    const loadImages = async () => {
      const images: { satellite?: string, logo?: string } = {};
      
      if (farm.imageUrl) {
        const sat = await imageUrlToBase64(farm.imageUrl);
        if (sat) images.satellite = sat;
      }
      
      if (farm.logoUrl) {
        const logo = await imageUrlToBase64(farm.logoUrl);
        if (logo) images.logo = logo;
      }
      
      setPdfImages(images);
    };
    loadImages();
  }, [farm]);

  useEffect(() => {
    const generateQR = async () => {
      if (!shareUrl) return;
      try {
        const url = await QRCode.toDataURL(shareUrl, { width: 400, margin: 1, color: { dark: '#15803d', light: '#ffffff' } });
        setQrDataUrl(url);
      } catch (err) { console.error("QR Error", err); }
    };
    generateQR();
  }, [shareUrl]);

  // --- Helpers ---
  const t = (key: keyof typeof TRANSLATIONS['en']) => TRANSLATIONS[language][key];
  const isSectionActive = (id: string) => activeSections.includes(id);

  const toggleSection = (id: string) => {
    setActiveSections(prev => prev.includes(id) ? prev.filter(x => x !== id) : [...prev, id]);
  };

  const toggleCsvColumn = (id: string) => {
    setCsvColumns(prev => prev.includes(id) ? prev.filter(x => x !== id) : [...prev, id]);
  };

  // --- Generators ---
  const generatePDF = () => {
    // Robust initialization of jsPDF
    // @ts-ignore
    const doc = new jsPDF({
      orientation: pdfOrientation === 'p' ? 'portrait' : 'landscape',
      unit: 'mm',
      format: 'a4'
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const contentWidth = pageWidth - (margin * 2);
    
    // Global Scaling Helper
    const s = (val: number) => val * pdfScale;
    let yPos = margin;

    // Helper to check page break
    const checkPageBreak = (needed: number) => {
      if (yPos + needed > pageHeight - margin) {
        doc.addPage();
        yPos = margin;
        return true;
      }
      return false;
    };

    // Use healthScore from new type or fallback
    const score = report.healthScore ?? report.overall_health_score ?? 0;
    const diagnosis = report.primaryDiagnosis ?? report.primary_stress ?? "Unknown";
    const explanation = report.detailedExplanation ?? report.explanation ?? "";
    const plan = report.monitoringPlan ?? report.monitoring_plan ?? "";

    // Set Font Globally
    doc.setFont(pdfFont);

    // Header with Logo
    doc.setFont(pdfFont, "bold");
    doc.setFontSize(s(22));
    doc.setTextColor(21, 128, 61);
    
    const title = t('title');
    doc.text(title, margin, yPos + s(5));
    
    // Farm Logo
    if (pdfImages.logo) {
      const logoSize = s(15);
      doc.addImage(pdfImages.logo, 'PNG', pageWidth - margin - logoSize, margin, logoSize, logoSize);
    }
    
    yPos += s(10);

    doc.setFont(pdfFont, "normal");
    doc.setFontSize(s(10));
    doc.setTextColor(100, 100, 100);
    doc.text(`${t('generated')} ${new Date().toLocaleDateString()}`, margin, yPos);
    yPos += s(10);
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, yPos, pageWidth - margin, yPos);
    yPos += s(15);

    // Dynamic 2-column layout X position
    const col2X = margin + (contentWidth / 2);

    // Section: Farm Details + Image
    if (isSectionActive('details')) {
        const detailsHeight = s(50);
        // Add extra height if satellite image is present
        const sectionHeight = pdfImages.satellite ? detailsHeight + s(70) : detailsHeight; 
        
        checkPageBreak(sectionHeight);
        
        doc.setFontSize(s(14));
        doc.setTextColor(50, 50, 50);
        doc.setFont(pdfFont, "bold");
        doc.text(t('farmDetails'), margin, yPos);
        yPos += s(8);
        
        doc.setFont(pdfFont, "normal");
        doc.setFontSize(s(11));

        doc.text(`${farm.name}`, margin, yPos);
        yPos += s(6);
        doc.text(`${t('location')}: ${farm.location}`, margin, yPos);
        doc.text(`${t('date')}: ${farm.date}`, col2X, yPos);
        yPos += s(6);
        doc.text(`${t('crop')}: ${farm.crop}`, margin, yPos);
        doc.text(`${t('size')}: ${farm.sizeHa} ha`, col2X, yPos);
        yPos += s(6);
        if (farm.gustWindSpeed) {
             doc.text(`${t('gust')}: ${farm.gustWindSpeed} ${farm.gustWindSpeedUnit || 'km/h'}`, margin, yPos);
        }
        yPos += s(8);

        // Satellite Image
        if (pdfImages.satellite) {
            const imgH = s(60);
            // 16:9 ratio approximately
            const imgW = Math.min(contentWidth, imgH * (16/9)); 
            const imgX = margin + (contentWidth - imgW) / 2; // Center image
            
            checkPageBreak(imgH + s(10));
            try {
              doc.addImage(pdfImages.satellite, 'JPEG', imgX, yPos, imgW, imgH);
              doc.setDrawColor(220, 220, 220);
              doc.rect(imgX, yPos, imgW, imgH); // Border
              yPos += imgH + s(10);
            } catch (e) {
              console.warn("Could not add satellite image to PDF", e);
            }
        }
        
        yPos += s(5);
    }

    // Section: Weather & Soil
    if (isSectionActive('metrics')) {
        checkPageBreak(s(40));
        doc.setFontSize(s(14));
        doc.setFont(pdfFont, "bold");
        doc.setTextColor(21, 128, 61);
        doc.text(t('soil'), margin, yPos);
        yPos += s(8);
        doc.setFontSize(s(11));
        doc.setTextColor(50, 50, 50);
        doc.setFont(pdfFont, "normal");
        
        doc.text(`${t('ph')}: ${farm.soil.ph}`, margin, yPos);
        doc.text(`${t('nitrogen')}: ${farm.soil.nitrogen} ppm`, col2X, yPos);
        yPos += s(6);
        doc.text(`${t('moisture')}: ${farm.weather.soilMoisture}%`, margin, yPos);
        doc.text(`${t('phosphorus')}: ${farm.soil.phosphorus} ppm`, col2X, yPos);
        yPos += s(6);
        doc.text(`${t('organic')}: ${farm.soil.organicMatter}%`, margin, yPos);
        doc.text(`${t('potassium')}: ${farm.soil.potassium} ppm`, col2X, yPos);
        yPos += s(15);
    }

    // Section: Health
    if (isSectionActive('health')) {
        checkPageBreak(s(50));
        doc.setFillColor(245, 245, 244);
        doc.roundedRect(margin, yPos, contentWidth, s(40), 3, 3, 'F');
        
        doc.setFont(pdfFont, "bold");
        doc.setTextColor(21, 128, 61);
        doc.setFontSize(s(12));
        doc.text(t('healthIndex'), margin + 5, yPos + s(10));
        doc.setFontSize(s(24));
        const scoreColor = score > 70 ? [34, 197, 94] : score > 40 ? [234, 179, 8] : [239, 68, 68];
        doc.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
        doc.text(`${score}/100`, margin + 5, yPos + s(25));

        doc.setFontSize(s(12));
        doc.setTextColor(80, 80, 80);
        doc.text(`${t('primaryStress')}:`, margin + 80, yPos + s(10));
        doc.setFont(pdfFont, "normal");
        const diagSplit = doc.splitTextToSize(diagnosis, contentWidth - 90);
        doc.text(diagSplit, margin + 80, yPos + s(18));
        
        yPos += s(50);

        // Chart Area (Manual Drawing for Robustness)
        if (trendData && trendData.length > 0) {
            const chartH = s(50); // Increased height
            const chartBottomPadding = s(15);
            const totalChartHeight = chartH + chartBottomPadding + s(20);
            
            checkPageBreak(totalChartHeight); 
            yPos += s(5);
            doc.setFontSize(s(12)); doc.setFont(pdfFont, "bold"); doc.setTextColor(50, 50, 50);
            doc.text("Health Trend (Last 30 Days)", margin, yPos);
            yPos += s(10);
            
            const chartW = contentWidth; 
            const chartY = yPos;
            const chartBottomY = chartY + chartH;

            // Background
            doc.setFillColor(250, 250, 250); 
            doc.rect(margin, chartY, chartW, chartH, 'F');
            
            // Axes
            doc.setDrawColor(200, 200, 200); 
            doc.setLineWidth(s(0.1));
            doc.line(margin, chartBottomY, margin + chartW, chartBottomY); // X axis
            doc.line(margin, chartY, margin, chartBottomY); // Y axis
            
            // Grid lines (horizontal)
            for(let j=1; j<4; j++) {
                const ly = chartY + (chartH * j / 4);
                doc.setDrawColor(230, 230, 230);
                doc.line(margin, ly, margin + chartW, ly);
            }

            const getX = (i: number) => margin + (i / (trendData.length - 1)) * chartW;
            const getYScore = (val: number) => chartBottomY - ((val / 100) * chartH);
            const getYNDVI = (val: number) => chartBottomY - (val * chartH); // NDVI 0-1 maps to full height
            
            // Draw Score Line
            doc.setDrawColor(34, 197, 94); doc.setLineWidth(s(0.8));
            for (let i = 0; i < trendData.length - 1; i++) {
                const x1 = getX(i);
                const y1 = getYScore(trendData[i].healthScore);
                const x2 = getX(i+1);
                const y2 = getYScore(trendData[i+1].healthScore);
                // Simple clamp to prevent drawing outside box
                if (y1 >= chartY && y1 <= chartBottomY && y2 >= chartY && y2 <= chartBottomY) {
                    doc.line(x1, y1, x2, y2);
                }
            }
            
            // Draw NDVI Line
            doc.setDrawColor(59, 130, 246); doc.setLineWidth(s(0.5)); doc.setLineDashPattern([2, 2], 0);
            for (let i = 0; i < trendData.length - 1; i++) {
                const x1 = getX(i);
                const y1 = getYNDVI(trendData[i].ndvi);
                const x2 = getX(i+1);
                const y2 = getYNDVI(trendData[i+1].ndvi);
                if (y1 >= chartY && y1 <= chartBottomY && y2 >= chartY && y2 <= chartBottomY) {
                    doc.line(x1, y1, x2, y2);
                }
            }
            doc.setLineDashPattern([], 0);
            
            // X-Axis Labels (Date)
            doc.setFontSize(s(7)); doc.setTextColor(150, 150, 150);
            const labelStep = Math.ceil(trendData.length / 6);
            for(let i=0; i<trendData.length; i += labelStep) {
                doc.text(trendData[i].date, getX(i), chartBottomY + s(5), { align: 'center' });
            }

            yPos = chartBottomY + s(10);
            doc.setFontSize(s(8)); doc.setFont(pdfFont, "normal");
            doc.setTextColor(34, 197, 94); doc.text("● Health Score (0-100)", margin, yPos);
            doc.setTextColor(59, 130, 246); doc.text("● NDVI Index (0-1)", margin + s(40), yPos);
            yPos += s(10);
        }
        
        // Summary
        checkPageBreak(s(30));
        doc.setFontSize(s(14));
        doc.setFont(pdfFont, "bold");
        doc.setTextColor(21, 128, 61);
        doc.text(t('summary'), margin, yPos);
        yPos += s(8);
        doc.setFontSize(s(11));
        doc.setTextColor(0,0,0);
        doc.setFont(pdfFont, "normal");
        const splitSummary = doc.splitTextToSize(explanation, contentWidth);
        
        // Check if summary fits, otherwise page break before starting
        if (checkPageBreak(splitSummary.length * s(5) + s(10))) {
             doc.text(splitSummary, margin, yPos);
        } else {
             // Basic pagination for long summary text
             let lineOffset = 0;
             while (lineOffset < splitSummary.length) {
                 const availableH = pageHeight - margin - yPos;
                 const linesCanFit = Math.floor(availableH / s(5));
                 
                 const chunk = splitSummary.slice(lineOffset, lineOffset + linesCanFit);
                 doc.text(chunk, margin, yPos);
                 
                 lineOffset += linesCanFit;
                 if (lineOffset < splitSummary.length) {
                     doc.addPage();
                     yPos = margin;
                 } else {
                     yPos += chunk.length * s(5);
                 }
             }
        }
        yPos += s(10);
    }

    // Section: Interventions (Robust Wrapping)
    if (isSectionActive('interventions')) {
        checkPageBreak(s(30));
        doc.setFontSize(s(14));
        doc.setFont(pdfFont, "bold");
        doc.setTextColor(21, 128, 61);
        doc.text(t('interventions'), margin, yPos);
        yPos += s(10);

        (report.interventions || []).forEach((item, i) => {
            const title = item.title || item.action || `Intervention ${i+1}`;
            
            // Text Wrapping Calculations
            doc.setFontSize(s(12)); doc.setFont(pdfFont, "bold");
            const titleLines = doc.splitTextToSize(`${i + 1}. ${title}`, contentWidth);
            
            doc.setFontSize(s(10)); doc.setFont(pdfFont, "normal");
            const goalLines = item.goal ? doc.splitTextToSize(`Goal: ${item.goal}`, contentWidth) : [];
            const impactLines = doc.splitTextToSize(`${t('impact')}: ${item.impact}`, contentWidth);
            
            let matLines: string[] = [];
            if (item.materials && item.materials.length > 0) {
                const matText = item.materials.join(', ');
                matLines = doc.splitTextToSize(`Materials: ${matText}`, contentWidth);
            }

            const lineHeight = s(5);
            const blockPadding = s(4);
            const totalBlockHeight = (titleLines.length * s(6)) + 
                                     (goalLines.length * lineHeight) + 
                                     (impactLines.length * lineHeight) + 
                                     (matLines.length * lineHeight) +
                                     s(15); // Meta line + spacing

            // Ensure we don't break inside a block if possible
            checkPageBreak(totalBlockHeight);

            // Render Block
            doc.setFontSize(s(12)); doc.setFont(pdfFont, "bold"); doc.setTextColor(0, 0, 0);
            doc.text(titleLines, margin, yPos);
            yPos += titleLines.length * s(6) + blockPadding;

            if (goalLines.length > 0) {
                doc.setFont(pdfFont, "normal"); doc.setFontSize(s(10)); doc.setTextColor(80, 80, 80);
                doc.text(goalLines, margin, yPos);
                yPos += goalLines.length * lineHeight + blockPadding;
            }

            doc.setFont(pdfFont, "normal"); doc.setFontSize(s(10)); doc.setTextColor(80, 80, 80);
            doc.text(impactLines, margin, yPos);
            yPos += impactLines.length * lineHeight + blockPadding;

            if (matLines.length > 0) {
                doc.setTextColor(50, 50, 50);
                doc.text(matLines, margin, yPos);
                yPos += matLines.length * lineHeight + blockPadding;
            }

            // Meta line
            doc.setTextColor(50, 50, 50); doc.setFont(pdfFont, "bold");
            const meta = `${t('timing')}: ${item.timing || 'Immediate'} | ${t('cost')}: ${item.cost || 'Medium'} | Conf: ${Math.round(item.confidence || 0)}%`;
            doc.text(meta, margin, yPos);
            
            yPos += s(12); // Space between items
        });
    }

    // Section: Plan
    if (isSectionActive('plan')) {
        checkPageBreak(s(30));
        doc.setFontSize(s(14));
        doc.setFont(pdfFont, "bold");
        doc.setTextColor(21, 128, 61);
        doc.text(t('plan'), margin, yPos);
        yPos += s(8);
        doc.setFontSize(s(11));
        doc.setTextColor(0,0,0);
        doc.setFont(pdfFont, "normal");
        const splitPlan = doc.splitTextToSize(plan, contentWidth);
        
        let lineOffset = 0;
        while (lineOffset < splitPlan.length) {
             const remainingSpace = pageHeight - margin - yPos;
             const linesThatFit = Math.floor(remainingSpace / s(5));
             
             // If extremely tight space (e.g. < 3 lines), just break page immediately for cleanliness
             if (linesThatFit < 3) {
                 doc.addPage();
                 yPos = margin;
                 continue;
             }

             const linesChunk = splitPlan.slice(lineOffset, lineOffset + linesThatFit);
             doc.text(linesChunk, margin, yPos);
             yPos += linesChunk.length * s(5);
             lineOffset += linesThatFit;
             
             if (lineOffset < splitPlan.length) {
                 doc.addPage();
                 yPos = margin;
             }
        }
        yPos += s(10);
    }

    // QR Code Section - Robust Placement
    if (qrDataUrl) {
        const qrBoxHeight = s(65);
        checkPageBreak(qrBoxHeight);
        
        yPos += s(5);
        doc.setFillColor(248, 250, 252);
        doc.roundedRect(margin, yPos, contentWidth, qrBoxHeight, 3, 3, 'F');
        doc.setDrawColor(226, 232, 240);
        doc.roundedRect(margin, yPos, contentWidth, qrBoxHeight, 3, 3, 'S');

        const innerX = margin + s(8);
        const innerY = yPos + s(8);

        doc.setFont(pdfFont, "bold"); doc.setFontSize(s(14)); doc.setTextColor(30, 41, 59);
        doc.text("Share Report with Advisors", innerX, innerY);

        const qrSize = s(40);
        const colSplit = innerX + qrSize + s(15);

        doc.addImage(qrDataUrl, 'PNG', innerX, innerY + s(5), qrSize, qrSize);
        doc.setFontSize(s(8)); doc.setFont(pdfFont, "normal"); doc.setTextColor(100, 116, 139);
        doc.text("Scan to view full report on mobile", innerX + (qrSize/2), innerY + qrSize + s(8), { align: 'center' });

        doc.setFont(pdfFont, "bold"); doc.setFontSize(s(10)); doc.setTextColor(51, 65, 85);
        doc.text("How to Share:", colSplit, innerY + s(5));

        doc.setFont(pdfFont, "normal"); doc.setFontSize(s(9)); doc.setTextColor(71, 85, 105);
        const steps = [
            "1. Scan QR with phone camera or WhatsApp.",
            `2. Opens shareable report with ${farm.name.substring(0, 25)}${farm.name.length>25?'...':''} details.`,
            `3. Forward to co-op/advisor (score: ${score}/100).`,
            "4. They see stress diagnosis + recommendations.",
            "5. Track progress—re-share after fixes!"
        ];

        let stepY = innerY + s(12);
        steps.forEach(step => {
            const stepLines = doc.splitTextToSize(step, contentWidth - (colSplit - margin) - s(5));
            doc.text(stepLines, colSplit, stepY);
            stepY += stepLines.length * s(5);
        });
        yPos += qrBoxHeight + s(5);
    }

    const pageCount = doc.getNumberOfPages();
    for(let i=1; i<=pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(s(8));
        doc.setTextColor(150,150,150);
        doc.text(t('footer'), margin, pageHeight - 10);
        doc.text(`Page ${i}/${pageCount}`, pageWidth - margin, pageHeight - 10, {align: 'right'});
    }

    return doc;
  };

  const generateExcel = () => {
    const score = report.healthScore ?? report.overall_health_score ?? 0;
    const diagnosis = report.primaryDiagnosis ?? report.primary_stress ?? "Unknown";
    const explanation = report.detailedExplanation ?? report.explanation ?? "";
    const isSpacious = xlsxLayout === 'spacious';

    const rows = [];
    
    if (includeMetadata) {
        rows.push([t('title')]);
        rows.push([`${t('generated')}: ${new Date().toLocaleDateString()}`]);
        rows.push([`${t('shareLink')}:`, shareUrl]); // Include Share URL
        if(isSpacious) rows.push([]);
    }

    if (isSectionActive('details')) {
        rows.push([t('farmDetails').toUpperCase()]);
        rows.push([t('location'), farm.name]);
        rows.push([t('crop'), farm.crop]);
        rows.push([t('size'), `${farm.sizeHa} ha`]);
        rows.push([t('gust'), `${farm.gustWindSpeed || 0} ${farm.gustWindSpeedUnit || 'km/h'}`]);
        if(isSpacious) rows.push([]);
    }

    if (isSectionActive('metrics')) {
        rows.push([t('soil').toUpperCase()]);
        rows.push([t('ph'), farm.soil.ph]);
        rows.push([t('nitrogen'), farm.soil.nitrogen]);
        rows.push([t('phosphorus'), farm.soil.phosphorus]);
        rows.push([t('potassium'), farm.soil.potassium]);
        rows.push([t('moisture'), farm.weather.soilMoisture]);
        if(isSpacious) rows.push([]);
    }

    if (isSectionActive('health')) {
        rows.push([t('healthIndex').toUpperCase()]);
        rows.push([t('healthIndex'), score]);
        rows.push([t('primaryStress'), diagnosis]);
        rows.push([t('summary'), explanation]);
        if(isSpacious) rows.push([]);
    }

    if (isSectionActive('interventions')) {
        rows.push([t('interventions').toUpperCase()]);
        rows.push([t('action'), t('timing'), t('cost'), t('impact'), t('materials')]);
        (report.interventions || []).forEach(i => {
            rows.push([i.title || i.action, i.timing || "Immediate", i.cost || "Medium", i.impact, (i.materials || []).join(', ')]);
        });
        if(isSpacious) rows.push([]);
    }

    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.aoa_to_sheet(rows);

    // Apply Layout Settings (Row Height & Col Width)
    // Note: This modifies the sheet object directly
    if (isSpacious) {
        // Set column widths
        ws['!cols'] = [
            { wch: 30 }, // A
            { wch: 25 }, // B
            { wch: 20 }, // C
            { wch: 50 }, // D (Impact)
            { wch: 40 }  // E (Materials)
        ];
        
        // Set row heights
        if (!ws['!rows']) ws['!rows'] = [];
        for (let i = 0; i < rows.length; i++) {
            // Header rows get more height
            if (rows[i][0] && typeof rows[i][0] === 'string' && rows[i][0] === rows[i][0].toUpperCase() && rows[i].length === 1) {
                ws['!rows'][i] = { hpx: 30 }; 
            } else {
                ws['!rows'][i] = { hpx: 24 }; // Standard spacious row
            }
        }
    } else {
        // Compact default
        ws['!cols'] = [{ wch: 20 }, { wch: 15 }, { wch: 15 }, { wch: 30 }, { wch: 30 }];
    }

    XLSX.utils.book_append_sheet(wb, ws, xlsxSheetName || 'Report');
    return wb;
  };

  const escapeCSV = (val: string | number | undefined) => {
    if (val === undefined || val === null) return '';
    const str = String(val);
    const escaped = str.replace(/"/g, '""');
    return `"${escaped}"`;
  };

  const generateCSV = () => {
    const sep = csvDelimiter;
    let rows: string[] = [];

    if (includeMetadata) {
        rows.push(escapeCSV(t('title')));
        rows.push(`${escapeCSV(t('generated'))}${sep}${escapeCSV(new Date().toLocaleDateString())}`);
        rows.push(`${escapeCSV(t('shareLink'))}${sep}${escapeCSV(shareUrl)}`); // Include Share URL
        rows.push("");
    }

    // ... (rest of CSV generation logic remains same) ...
    if (isSectionActive('details')) {
        rows.push(escapeCSV(t('farmDetails').toUpperCase()));
        rows.push(`${escapeCSV(t('location'))}${sep}${escapeCSV(farm.name)}`);
        rows.push(`${escapeCSV(t('crop'))}${sep}${escapeCSV(farm.crop)}`);
        const gustStr = farm.gustWindSpeed ? `${farm.gustWindSpeed} ${farm.gustWindSpeedUnit || 'km/h'}` : '';
        rows.push(`${escapeCSV(t('gust'))}${sep}${escapeCSV(gustStr)}`);
        rows.push("");
    }

    if (isSectionActive('metrics')) {
         rows.push(escapeCSV(t('soil').toUpperCase()));
         rows.push(`${escapeCSV(t('ph'))}${sep}${escapeCSV(farm.soil.ph)}`);
         rows.push(`${escapeCSV(t('nitrogen'))}${sep}${escapeCSV(farm.soil.nitrogen)}`);
         rows.push(`${escapeCSV(t('phosphorus'))}${sep}${escapeCSV(farm.soil.phosphorus)}`);
         rows.push("");
    }

    if (isSectionActive('interventions')) {
        rows.push(escapeCSV(t('interventions').toUpperCase()));
        const headerRow = csvColumns.map(colId => {
             const label = t(colId as keyof typeof TRANSLATIONS['en']) || colId;
             return escapeCSV(label); 
        }).join(sep);
        rows.push(headerRow);

        (report.interventions || []).forEach(i => {
             const rowData = csvColumns.map(colId => {
                 switch(colId) {
                     case 'action': return i.title || i.action;
                     case 'timing': return i.timing || "Immediate";
                     case 'cost': return i.cost || "Medium";
                     case 'impact': return i.impact;
                     case 'confidence': return i.confidence ? Math.round(i.confidence) + '%' : '';
                     case 'materials': return (i.materials || []).join(', ');
                     default: return '';
                 }
             });
             rows.push(rowData.map(val => escapeCSV(val)).join(sep));
        });
    }

    return rows.join('\n');
  };

  const generateJSON = () => {
    const data: any = {};
    if (includeMetadata) data.meta = { 
        generated: new Date(), 
        app: "CropHealth",
        shareUrl: shareUrl // Include Share URL
    };
    if (isSectionActive('details')) data.farm = farm;
    if (isSectionActive('metrics')) data.env = { weather: farm.weather, soil: farm.soil };
    if (isSectionActive('health')) data.analysis = { 
        score: report.healthScore ?? report.overall_health_score, 
        diagnosis: report.detailedExplanation ?? report.explanation 
    };
    if (isSectionActive('interventions')) data.interventions = report.interventions || [];
    if (isSectionActive('plan')) data.plan = report.monitoringPlan ?? report.monitoring_plan;
    return JSON.stringify(data, null, jsonPretty ? 2 : 0);
  };

  // --- Live Preview ---
  useEffect(() => {
    try {
        if (mode === 'share') {
            const doc = generatePDF();
            const blob = doc.output('blob');
            const url = URL.createObjectURL(blob);
            setPreviewContent(url);
            return () => URL.revokeObjectURL(url);
        } else {
            if (format === 'pdf') {
                const doc = generatePDF();
                const blob = doc.output('blob');
                const url = URL.createObjectURL(blob);
                setPreviewContent(url);
                return () => URL.revokeObjectURL(url);
            } else if (format === 'xlsx') {
                const wb = generateExcel();
                const ws = wb.Sheets[xlsxSheetName || 'Report'];
                let html = XLSX.utils.sheet_to_html(ws, { editable: false });
                
                // Inject styles for preview spacing based on layout mode
                if (xlsxLayout === 'spacious') {
                    // Inject padding into cells for spacious look
                    html = html.replace(/<td/g, '<td style="padding: 12px 16px; border: 1px solid #e5e7eb;"');
                    html = html.replace(/<table/g, '<table style="border-collapse: collapse; width: 100%; font-family: sans-serif;"');
                } else {
                    html = html.replace(/<td/g, '<td style="padding: 4px 8px; border: 1px solid #e5e7eb;"');
                    html = html.replace(/<table/g, '<table style="border-collapse: collapse; width: 100%; font-family: sans-serif;"');
                }
                
                setPreviewContent(html);
            } else if (format === 'csv') {
                setPreviewContent(generateCSV());
            } else {
                setPreviewContent(generateJSON());
            }
        }
    } catch (e) {
        console.error("Preview Generation Error", e);
    }
  }, [mode, format, language, activeSections, includeMetadata, pdfFont, pdfScale, pdfOrientation, csvDelimiter, csvColumns, xlsxSheetName, xlsxLayout, jsonPretty, report, farm, qrDataUrl, pdfImages]);


  // --- Handlers ---
  const handleDownload = () => {
      try {
        const date = new Date().toISOString().slice(0,10);
        const filename = `CropHealth_${farm.id}_${date}`;

        if (format === 'pdf') {
            const doc = generatePDF();
            doc.save(`${filename}.pdf`);
        } else if (format === 'xlsx') {
            const wb = generateExcel();
            safeWriteExcelFile(wb, `${filename}.xlsx`);
        } else if (format === 'csv') {
            const blob = new Blob([generateCSV()], { type: 'text/csv;charset=utf-8' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `${filename}.csv`;
            a.click();
        } else {
            const blob = new Blob([generateJSON()], { type: 'application/json' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `${filename}.json`;
            a.click();
        }
      } catch (e) {
          console.error("Download Error", e);
          alert("Failed to download report. Please try another format.");
      }
  };

  return (
    <div 
        className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-stone-900/80 backdrop-blur-md transition-opacity"
        role="dialog"
        aria-modal="true"
    >
      <div 
        ref={modalRef}
        tabIndex={-1}
        className="bg-white rounded-2xl shadow-2xl w-full max-w-7xl overflow-hidden flex flex-col md:flex-row h-[90vh] outline-none"
      >
        {/* SIDEBAR: Controls */}
        <div className="w-full md:w-[400px] flex flex-col border-r border-stone-200 bg-stone-50 shrink-0 z-10">
            {/* Sidebar Header */}
            <div className="px-6 py-4 border-b border-stone-200 bg-white flex justify-between items-center">
                <h2 className="font-bold text-stone-800 text-lg flex items-center gap-2">
                    <span className="w-8 h-8 rounded bg-agri-600 text-white flex items-center justify-center shadow-agri-600/30 shadow-md">
                        <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" /></svg>
                    </span>
                    Share & Export
                </h2>
                <button onClick={onClose} className="text-stone-400 hover:text-stone-600 transition-colors bg-stone-100 hover:bg-stone-200 p-1.5 rounded-full">
                    <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
                </button>
            </div>

            {/* Mode Switcher */}
            <div className="px-6 py-4 bg-white border-b border-stone-200">
                <div className="flex bg-stone-100 p-1 rounded-xl">
                    <button 
                        onClick={() => setMode('share')}
                        className={`flex-1 py-2 rounded-lg text-sm font-bold transition-all ${mode === 'share' ? 'bg-white shadow-sm text-agri-700' : 'text-stone-500 hover:text-stone-700'}`}
                    >
                        Share Options
                    </button>
                    <button 
                        onClick={() => setMode('export')}
                        className={`flex-1 py-2 rounded-lg text-sm font-bold transition-all ${mode === 'export' ? 'bg-white shadow-sm text-blue-700' : 'text-stone-500 hover:text-stone-700'}`}
                    >
                        Export Options
                    </button>
                </div>
            </div>

            {/* Scrollable Controls */}
            <div className="flex-1 overflow-y-auto p-6 space-y-8 custom-scrollbar">
                
                {/* MODE: SHARE OPTIONS */}
                {mode === 'share' && (
                    <div className="space-y-6 animate-fade-in">
                        <section>
                            <label className="text-[11px] font-bold text-stone-400 uppercase tracking-wider block mb-3">QR Access Code</label>
                            <div className="bg-white p-4 rounded-xl border border-stone-200 flex flex-col items-center">
                                {qrDataUrl && <img src={qrDataUrl} alt="QR Code" className="w-48 h-48 mb-4 mix-blend-multiply" />}
                                <p className="text-center text-sm text-stone-500 font-medium">Scan to view on mobile</p>
                            </div>
                        </section>

                        <section className="space-y-3">
                            <label className="text-[11px] font-bold text-stone-400 uppercase tracking-wider block">Public Link</label>
                            <div className="flex gap-2">
                                <input 
                                    readOnly 
                                    value={shareUrl} 
                                    className="flex-1 bg-stone-50 border border-stone-200 rounded-lg px-3 py-2 text-sm text-stone-600 outline-none" 
                                />
                                <button 
                                    onClick={onCopy}
                                    className={`px-3 rounded-lg border transition-colors flex items-center justify-center
                                        ${isCopied ? 'bg-green-50 border-green-200 text-green-600' : 'bg-white border-stone-200 text-stone-500 hover:bg-stone-50'}`}
                                >
                                    {isCopied ? (
                                        <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
                                    ) : (
                                        <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2" /></svg>
                                    )}
                                </button>
                            </div>
                        </section>

                        <section className="space-y-3">
                            <label className="text-[11px] font-bold text-stone-400 uppercase tracking-wider block">Email Sharing</label>
                            <button 
                                onClick={onEmail}
                                className="w-full py-2.5 bg-stone-800 hover:bg-stone-900 text-white rounded-lg text-sm font-semibold flex items-center justify-center gap-2 transition-colors"
                            >
                                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" /></svg>
                                Share via Email
                            </button>
                        </section>
                    </div>
                )}

                {/* MODE: EXPORT OPTIONS */}
                {mode === 'export' && (
                    <div className="space-y-8 animate-fade-in">
                        {/* 1. Format Tabs */}
                        <div className="p-1 bg-stone-200/50 rounded-xl flex gap-1">
                            {['pdf', 'xlsx', 'csv', 'json'].map(f => (
                                <button 
                                    key={f}
                                    onClick={() => setFormat(f as any)}
                                    className={`flex-1 py-2 rounded-lg text-xs font-bold uppercase tracking-wide transition-all
                                        ${format === f 
                                            ? 'bg-white text-blue-700 shadow-sm transform scale-[1.02]' 
                                            : 'text-stone-500 hover:text-stone-700 hover:bg-stone-200/50'
                                        }`}
                                >
                                    {f}
                                </button>
                            ))}
                        </div>

                        {/* 2. Global Settings */}
                        <section>
                            <label className="text-[11px] font-bold text-stone-400 uppercase tracking-wider mb-3 block">Language & Locale</label>
                            <div className="flex flex-wrap gap-2">
                                {[{id:'en', l:'English'}, {id:'es', l:'Español'}, {id:'pt', l:'Português'}, {id:'hi', l:'Hindi'}].map(lang => (
                                    <button
                                        key={lang.id}
                                        onClick={() => setLanguage(lang.id as Language)}
                                        className={`px-3 py-1.5 rounded-md text-xs font-medium border transition-colors
                                            ${language === lang.id ? 'bg-blue-50 text-blue-700 border-blue-200 ring-1 ring-blue-200' : 'bg-white text-stone-600 border-stone-200 hover:bg-stone-50'}`}
                                    >
                                        {lang.l}
                                    </button>
                                ))}
                            </div>
                        </section>

                        <section>
                            <label className="text-[11px] font-bold text-stone-400 uppercase tracking-wider mb-3 block">
                                {format === 'json' ? 'Included Data Fields' : 'Included Columns/Sections'}
                            </label>
                            
                            <div className="mb-3">
                                <label className="flex items-center gap-3 p-2 rounded-lg hover:bg-white border border-transparent hover:border-stone-100 transition-colors cursor-pointer">
                                    <input 
                                        type="checkbox" 
                                        checked={includeMetadata} 
                                        onChange={e => setIncludeMetadata(e.target.checked)}
                                        className="w-4 h-4 rounded text-blue-600 focus:ring-blue-500 border-stone-300"
                                    />
                                    <span className="text-sm text-stone-700 font-bold">Include Metadata (Headers)</span>
                                </label>
                            </div>

                            <div className="space-y-2 pl-2 border-l-2 border-stone-100 ml-1">
                                {SECTIONS.map(s => (
                                    <div key={s.id}>
                                        <label className="flex items-center gap-3 p-2 rounded-lg hover:bg-white border border-transparent hover:border-stone-100 transition-colors cursor-pointer group">
                                            <input 
                                                type="checkbox" 
                                                checked={activeSections.includes(s.id)} 
                                                onChange={() => toggleSection(s.id)}
                                                className="w-4 h-4 rounded text-blue-600 focus:ring-blue-500 border-stone-300"
                                            />
                                            <span className="text-sm text-stone-600 font-medium group-hover:text-stone-900">{s.label}</span>
                                        </label>
                                        
                                        {/* Sub-column selection for CSV/Interventions */}
                                        {s.id === 'interventions' && activeSections.includes('interventions') && format === 'csv' && (
                                            <div className="ml-8 mt-1 mb-2 grid grid-cols-2 gap-2 animate-fade-in">
                                                {INTERVENTION_COLUMNS.map(col => (
                                                    <label key={col.id} className="flex items-center gap-2 cursor-pointer">
                                                        <input 
                                                            type="checkbox" 
                                                            checked={csvColumns.includes(col.id)}
                                                            onChange={() => toggleCsvColumn(col.id)}
                                                            className="w-3 h-3 rounded text-blue-600 focus:ring-blue-500 border-stone-300"
                                                        />
                                                        <span className="text-xs text-stone-500">{col.label}</span>
                                                    </label>
                                                ))}
                                            </div>
                                        )}
                                    </div>
                                ))}
                            </div>
                        </section>

                        <hr className="border-stone-200" />

                        {/* 3. Format Specific Config */}
                        {format === 'pdf' && (
                            <section className="space-y-5 animate-fade-in">
                                <div>
                                    <label className="text-[11px] font-bold text-stone-400 uppercase tracking-wider mb-3 block">PDF Layout</label>
                                    <div className="flex bg-stone-100 p-1 rounded-lg mb-4">
                                        <button onClick={() => setPdfOrientation('p')} className={`flex-1 py-1.5 text-xs font-medium rounded ${pdfOrientation === 'p' ? 'bg-white shadow text-stone-800' : 'text-stone-500'}`}>Portrait</button>
                                        <button onClick={() => setPdfOrientation('l')} className={`flex-1 py-1.5 text-xs font-medium rounded ${pdfOrientation === 'l' ? 'bg-white shadow text-stone-800' : 'text-stone-500'}`}>Landscape</button>
                                    </div>
                                </div>

                                <div>
                                    <label className="text-[11px] font-bold text-stone-400 uppercase tracking-wider mb-3 block">Typography</label>
                                    <div className="space-y-3">
                                        <select 
                                            value={pdfFont} 
                                            onChange={e => setPdfFont(e.target.value)} 
                                            className="w-full bg-white border border-stone-200 rounded-lg px-3 py-2 text-sm text-stone-700 focus:border-blue-500 focus:outline-none"
                                        >
                                            {FONTS.map(f => <option key={f.value} value={f.value}>{f.label}</option>)}
                                        </select>
                                        
                                        <div className="bg-white p-3 rounded-lg border border-stone-200">
                                            <div className="flex justify-between text-xs mb-2">
                                                <span className="text-stone-500">Font Size Scale</span>
                                                <span className="font-mono text-stone-800">{Math.round(pdfScale * 100)}%</span>
                                            </div>
                                            <input 
                                                type="range" min="0.8" max="1.5" step="0.05" 
                                                value={pdfScale} 
                                                onChange={e => setPdfScale(parseFloat(e.target.value))}
                                                className="w-full h-1.5 bg-stone-100 rounded-lg appearance-none cursor-pointer accent-blue-600"
                                            />
                                            <div className="flex justify-between text-[10px] text-stone-400 mt-1">
                                                <span>Small</span>
                                                <span>Large</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </section>
                        )}

                        {format === 'csv' && (
                            <section className="animate-fade-in space-y-4">
                                <label className="text-[11px] font-bold text-stone-400 uppercase tracking-wider mb-2 block">CSV Configuration</label>
                                <div className="bg-white border border-stone-200 rounded-lg p-3">
                                    <label className="text-xs font-semibold text-stone-700 block mb-2">Delimiter Character</label>
                                    <select 
                                        value={csvDelimiter} 
                                        onChange={e => setCsvDelimiter(e.target.value as any)} 
                                        className="w-full bg-stone-50 border border-stone-200 rounded px-2 py-2 text-sm text-stone-700 focus:outline-none"
                                    >
                                        <option value=",">Comma (,)</option>
                                        <option value=";">Semicolon (;)</option>
                                        <option value={`\t`}>Tab (\t)</option>
                                    </select>
                                </div>
                            </section>
                        )}

                        {format === 'xlsx' && (
                            <section className="animate-fade-in space-y-4">
                                <label className="text-[11px] font-bold text-stone-400 uppercase tracking-wider mb-2 block">Excel Settings</label>
                                <div className="space-y-3">
                                    <div>
                                        <label className="text-xs font-semibold text-stone-600 block mb-1">Sheet Name</label>
                                        <input 
                                            type="text" 
                                            value={xlsxSheetName}
                                            onChange={e => setXlsxSheetName(e.target.value)}
                                            className="w-full bg-white border border-stone-200 rounded px-3 py-2 text-sm text-stone-800 focus:border-blue-500 focus:outline-none"
                                            placeholder="Report"
                                        />
                                    </div>
                                    <div>
                                        <label className="text-xs font-semibold text-stone-600 block mb-1">Layout Density</label>
                                        <div className="flex gap-2">
                                            <button 
                                                onClick={() => setXlsxLayout('compact')}
                                                className={`flex-1 py-1.5 text-xs border rounded ${xlsxLayout === 'compact' ? 'bg-blue-50 border-blue-500 text-blue-700' : 'bg-white border-stone-200 text-stone-600'}`}
                                            >
                                                Compact
                                            </button>
                                            <button 
                                                onClick={() => setXlsxLayout('spacious')}
                                                className={`flex-1 py-1.5 text-xs border rounded ${xlsxLayout === 'spacious' ? 'bg-blue-50 border-blue-500 text-blue-700' : 'bg-white border-stone-200 text-stone-600'}`}
                                            >
                                                Spacious
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </section>
                        )}

                        {format === 'json' && (
                            <section className="animate-fade-in">
                                <label className="text-[11px] font-bold text-stone-400 uppercase tracking-wider mb-3 block">JSON Formatting</label>
                                <div className="bg-white border border-stone-200 rounded-lg p-3">
                                    <label className="flex items-center gap-3 cursor-pointer">
                                        <div className={`w-10 h-6 rounded-full p-1 transition-colors ${jsonPretty ? 'bg-blue-500' : 'bg-stone-300'}`}>
                                            <div className={`w-4 h-4 bg-white rounded-full shadow-sm transition-transform ${jsonPretty ? 'translate-x-4' : 'translate-x-0'}`} />
                                        </div>
                                        <input type="checkbox" checked={jsonPretty} onChange={e => setJsonPretty(e.target.checked)} className="hidden" />
                                        <span className="text-sm font-medium text-stone-700">Pretty Print</span>
                                    </label>
                                    <p className="text-xs text-stone-400 mt-2 pl-1">Indents nested objects for readability.</p>
                                </div>
                            </section>
                        )}
                    </div>
                )}

            </div>

            {/* Sidebar Footer */}
            {mode === 'export' && (
                <div className="p-6 border-t border-stone-200 bg-white">
                    <button 
                        onClick={handleDownload}
                        className="w-full py-3.5 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-xl shadow-lg transition-all transform active:scale-[0.98] flex items-center justify-center gap-2"
                    >
                        <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                        Download {format.toUpperCase()}
                    </button>
                </div>
            )}
        </div>

        {/* RIGHT PANEL: Live Preview */}
        <div className="flex-1 bg-stone-100 flex flex-col min-w-0 h-full relative">
             <div className="h-14 border-b border-stone-200 bg-white/80 backdrop-blur-sm flex items-center px-6 justify-between shrink-0 sticky top-0 z-10">
                <div className="flex items-center gap-2">
                    <div className="w-2 h-2 rounded-full bg-red-500 animate-pulse"></div>
                    <span className="text-xs font-bold text-stone-500 uppercase tracking-wider">
                        {mode === 'share' ? 'Report Preview' : 'Export Preview'}
                    </span>
                </div>
                <div className="flex items-center gap-2">
                    <span className="text-[10px] text-stone-400 bg-stone-100 px-2 py-1 rounded font-mono">
                         {mode === 'share' || format === 'pdf' ? `${pdfOrientation === 'p' ? 'A4 Portrait' : 'A4 Landscape'}` : format.toUpperCase()}
                    </span>
                </div>
             </div>
             
             <div className="flex-1 overflow-auto p-4 md:p-8 flex items-center justify-center bg-stone-100">
                 {(mode === 'share' || (mode === 'export' && format === 'pdf')) && previewContent ? (
                     <iframe 
                        src={`${previewContent}#toolbar=0&navpanes=0&view=FitH`} 
                        className="w-full h-full shadow-2xl rounded-sm bg-white max-w-[800px] border border-stone-300 transition-all duration-300 ease-out"
                        title="PDF Preview"
                     />
                 ) : mode === 'export' && format === 'xlsx' && previewContent ? (
                     <div 
                        className="bg-white p-8 shadow-xl overflow-auto w-full max-w-[800px] h-full text-sm border border-stone-300 font-mono text-stone-600 whitespace-pre"
                        dangerouslySetInnerHTML={{ __html: previewContent }}
                     />
                 ) : (
                     <div className="w-full h-full max-w-[800px] bg-[#1e1e1e] rounded-xl shadow-2xl overflow-hidden flex flex-col border border-stone-700/50">
                         <div className="bg-[#252526] px-4 py-2 flex items-center gap-2 border-b border-black/20">
                             <div className="flex gap-1.5">
                                <div className="w-3 h-3 rounded-full bg-[#ff5f56]"></div>
                                <div className="w-3 h-3 rounded-full bg-[#ffbd2e]"></div>
                                <div className="w-3 h-3 rounded-full bg-[#27c93f]"></div>
                             </div>
                             <span className="ml-2 text-xs text-stone-500 font-mono">preview.{format}</span>
                         </div>
                         <div className="flex-1 overflow-auto p-4 custom-scrollbar">
                             <pre className="text-xs font-mono text-[#d4d4d4] leading-relaxed whitespace-pre-wrap break-all">
                                {previewContent}
                             </pre>
                         </div>
                     </div>
                 )}
             </div>
        </div>

      </div>
    </div>
  );
};

export default ShareReport;
