import { useState, useCallback } from 'react';
import { FarmData, HealthReport } from '../types';

export const useShareReport = (farm: FarmData, report: HealthReport | null) => {
  const [isCopied, setIsCopied] = useState(false);

  // Generate the share URL based on the current farm and report data
  const shareUrl = report 
    ? `https://crophealth.app/share/${farm.id}?score=${report.overall_health_score}` 
    : '';

  const copyToClipboard = useCallback(async () => {
    if (!shareUrl) return;
    
    try {
      await navigator.clipboard.writeText(shareUrl);
      setIsCopied(true);
      // Reset copied state after 2 seconds
      setTimeout(() => setIsCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy to clipboard:', err);
    }
  }, [shareUrl]);

  const shareViaEmail = useCallback(() => {
    if (!report) return;

    const subject = encodeURIComponent(`CropHealth Report: ${farm.name}`);
    const bodyText = `
Here is the CropHealth analysis report for ${farm.name}.

Analysis Date: ${farm.date}
Overall Health Score: ${report.overall_health_score}/100
Primary Diagnosis: ${report.primary_stress.toUpperCase()} Stress (${report.affected_percent}% affected)

View the full interactive report here:
${shareUrl}

Generated by CropHealth Monitor.
    `.trim();

    const body = encodeURIComponent(bodyText);
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  }, [farm, report, shareUrl]);

  return {
    shareUrl,
    isCopied,
    copyToClipboard,
    shareViaEmail
  };
};
